### ISSUE TITLE
Definir Módulos

### ISSUE THREAD

**Issue by Caldas** [SplunkGlobalDevs/Splunkorial-pt#1]
Definir os módulos que serão ensinados no Tutorial

--------

**Modulo 0 - Rodando Splunk Localmente**
- [ ] Instalando Docker #2 
- [ ] Rodando Splunk #4

**Module 1 -  Introducing Splunk**
- [ ] Entendendo usos com Splunk #5
- [ ] Explicando Splunk Apps #6
- [ ] Navegando pelo Splunk #7

--------

**AINDA PRECISA DE TRADUÇÃO**

**Module 2 - Searching**
- [ ] Run basic searches
- [ ] Use autocomplete to help build a search
- [ ] Set the time range of a search
- [ ] Identify the contents of search results
- [ ] Refine searches
- [ ] Use the timeline
- [ ] Work with events
- [ ] Control a search job
- [ ] Save search results

**Module 3 - Using Fields in Searching**
- [ ] Understand fields
- [ ] Use fields in searches
- [ ] Use the fields sidebar
- [ ] Use search modes (fast, verbose, and smart)

**Module 4 - Creating Reports and Dashboards**
- [ ] Save a search as a report
- [ ] Edit reports
- [ ] Create reports that display statistics (tables)
- [ ] Create reports that display visualizations (charts)
- [ ] Create a dashboard
- [ ] Add a report to a dashboard
- [ ] Edit a dashboard

**Module 5 - Splunk's Search Language Fundamentals**
- [ ] Understand the search pipeline
- [ ] Understand search syntax concepts
- [ ] Use the following commands to perform searches: tables, rename, fields, dedup, sort

**Module 6 - Using basic Transforming Commands**
- [ ] The top command
- [ ] The rare command
- [ ] The stats command

**Module 7 - Creating and Using Lookups**
- [ ] Describe lookups 
- [ ] Examine a lookup file example
- [ ] Create a lookup file and create a lookup definition
- [ ] Configure an automatic lookup
- [ ] Use the lookup in searches

**Module 8 - Creating Alerts and Scheduled Reports**
- [ ] Describe scheduled reports
- [ ] Configure scheduled reports
- [ ] Describe alerts
- [ ] Create alerts
- [ ] View fired alerts

**Module 9 - Creating and Using Macros**
- [ ] Describe macros
- [ ] Create and use a basic macro
- [ ] Define arguments and variables for a macro
- [ ] Add and use arguments with a macro

**Module 10 - Creating Data Models**
- [ ] Describe the relationship between data models and pivot
- [ ] Identify data model attributes
- [ ] Create a data modelUse a data model in pivot

**Comment by Caldas** [comment]
Partindo da premissa do [Splunk Fundamentals 1](https://www.splunk.com/en_us/training/free-courses/splunk-fundamentals-1.html) que é o curso oficial em inglês vamos assumir que esse projeto precisa ao menos ter todo esse conteúdo também disponibilizado
